# dataset
dataset: UNEOD
tokenize:
  conv: ltp
# dataloader
context_truncate: 1024
response_truncate: 1024
scale: 1
# model
conv_model: Transformer
token_emb_dim: 300
kg_emb_dim: 128
num_bases: 8
n_heads: 2
n_layers: 2
ffn_size: 300
dropout: 0.1
attention_dropout: 0.1
relu_dropout: 0.1
learn_positional_embeddings: true
embeddings_scale: true
reduction: false
n_positions: 1024
# optim
conv:
  epoch: 100
  batch_size: 16
  early_stop: False
  impatience: 5
  stop_mode: min
  optimizer:
    name: Adam
    lr: !!float 1e-3
  lr_scheduler:
    name: ReduceLROnPlateau
    patience: 3
    factor: 0.5